### PR TITLE
Made super cool python file

### PR DESCRIPTION
**Pull request by me-here**
Please review my code and let me know what is wrong!

### CODE REVIEW

**Comment by jyue86** [comment]
bwoah looks gud to me

**Comment by parsakmt** [comment]
omg this looks 11/10 plz teach me how to be this good

**Comment by jyue86** [comment]
b**** a** why does the code look worse /s

**Comment by me-here** [comment]
Can you took at this again? If it's good, merge it.

**Comment by parsakmt** [comment]
It looked better before but this is satisfactory adjacent

**Pull request merged**
